onlineapp/urls.py
from django.urls import path
from . import views
from onlineapp.views import *

from onlineapp.restAPI import *

app_name="onlineapp"

urlpatterns=[
    #path('jki/',views.my_html_view),
    #path('clg/<int:s_id>/',views.student_data),
    #path('mrks/',views.student_marks),
    #path('clgo/<int:c_id>/',views.clg_order),
    #path('testsession/',views.test_session),
    #path('',views.helloworld),
    #path('exce/',views.check_exception),

    path('clgs/',CollegeView.as_view(),name="colleges"),

    path('colleges/',CollegeListView.as_view(),name="college_html"),

    path('colleges/add',CreateCollegeView.as_view(),name="add_colleges"),

    path('colleges/<int:pk>/edit', UpdateCollegeView.as_view(), name="edit_college"),

    path('colleges/<int:pk>/delete', DeleteCollegeView.as_view(), name="delete_college"),


    path('colleges1/<int:pk>/', CollegeDetailView.as_view(), name="college_detail_html"),

    path('colleges1/<int:pk>/add', CreateStudentView.as_view(), name="college_detail.html"),

    path('colleges/<int:college_id>/edit/<int:pk>/', UpdateStudentView.as_view(), name='edit_student'),

    path('colleges/<int:college_id>/<int:pk>/delete', DeleteStudentView.as_view(), name='delete_student'),


    path('signup/',SignupController.as_view(),name="signup"),

    path('login/',LoginController.as_view(),name="login"),

    path('logout/',logout_user,name="logout"),





    path('api/v2/clg/', clgg_list),
    path('clg_detail/<int:pk>/', snippet_detail),

    path('std/', student_list),
    path('std_detail/<int:pk>/', Student_detail),

    path('clgst/<int:pk>/', StudentsOfClgView.as_view()),

    path('clgstudents/clg/<int:clg_id>/stdnt/<int:pk>/',college_detail),

    path('studentsinclg/clg/<int:clg_id>/stdnt/<int:pk>/',StudentMarksView.as_view())



]

onlineproject/urls.py
from django.contrib import admin
from django.urls import path,include
from rest_framework_jwt.views import obtain_jwt_token

from onlineapp import views
from django.conf import settings
from django.conf.urls import include, url
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('onlineapp/',include('onlineapp.urls')),

    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^', TemplateView.as_view(template_name="index.html")),

]


if settings.DEBUG:
   import debug_toolbar
   urlpatterns += [
       url(r'^__debug__/', include(debug_toolbar.urls)),
   ]

onlineapp/models.py
from django.db import models

# Create your models here.

class College(models.Model):
    name=models.CharField(max_length=128)
    location=models.CharField(max_length=64)
    acronym=models.CharField(max_length=8)
    contact=models.EmailField()

    def __str__(self):
        return self.acronym

class Student(models.Model):
    name=models.CharField(max_length=128)
    dob=models.DateField(null=True,blank=True)
    email=models.EmailField()
    db_folder=models.CharField(max_length=60)

    dropped_out=models.BooleanField(default=False)

    college = models.ForeignKey(College, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class MockTest1(models.Model):
    problem1 = models.IntegerField()
    problem2 = models.IntegerField()
    problem3 = models.IntegerField()
    problem4 = models.IntegerField()
    total = models.IntegerField()

    student = models.OneToOneField(Student, on_delete=models.CASCADE)

    def __str__(self):
        return f"Student {self.student.name} marks"

onlineapp/forms/college.py
from onlineapp.models import *
from django import forms

class Addcollege(forms.ModelForm):
    class Meta:
        model=College
        exclude={'id'}
        widgets={
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter name'}),
            'location':forms.TextInput(attrs={'class':'form-control','placeholder':'location'}),
            'acronym':forms.TextInput(attrs={'class':'form-control','placeholder':'acronym'}),
            'contact':forms.EmailInput(attrs={'class':'form-control','placeholder':'contact'})
        }

onlineapp/forms/mocktest.py
from django import forms
from onlineapp.models import *


class MockTestForm(forms.ModelForm):
    class Meta:
        model=MockTest1
        exclude=['id','total','student']
        widgets = {

            'problem1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Score in problem 1'}),

            'problem2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Score in problem 2'}),

            'problem3': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Score in problem 3'}),

            'problem4': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Score in problem 4'}),

        }

onlineapp/forms/student.py
from django import forms
from onlineapp.models import *

class studentform(forms.ModelForm):
    class Meta:
        model=Student
        exclude=['id','dob','college']
        widgets={
            'name':forms.TextInput(attrs={'class':'form-control','placeholder':'name'}),
            'email':forms.EmailInput(attrs={'class':'form-control','placeholder':'email'}),
            'db_folder':forms.TextInput(attrs={'class':'form-control','placeholder':'db_folder'}),
            'dropped_out':forms.CheckboxInput(attrs={'class':'form-control','placeholder':'dropped-out'})
        }

onlineapp/views/college.py
from onlineapp.models import *
from django.views import View
from onlineapp.models import *
from django.shortcuts import *
import ipdb
from django.views.generic import *
from django import forms
from onlineapp.forms import *
from django.urls import *
from django.contrib.auth.mixins import *
app_name="onlineapp"
class CollegeView(LoginRequiredMixin,View):
    login_url = "onlineapp:login"
    def get(self,request,*args,**kwargs):
        pass
        colleges=College.objects.all()

        return render(
            request,
            template_name='onlineapp/colleges.html',
            context={
                "jails":colleges

            }
        )

class CollegeListView(LoginRequiredMixin,ListView):
    login_url = "onlineapp:login"
    model = College
    context_object_name = 'jails'
    template_name = "college_list.html"



    def get_context_data(self, **kwargs):
        context = super(CollegeListView,self).get_context_data(**kwargs)

        #context['data']=self.model.objects.all().values('name','student__name','student__email','student__mocktest1__total')

        context.update({'user_permissions' : self.request.user.get_all_permissions})
        return context


class CollegeDetailView(LoginRequiredMixin,DetailView):
    login_url = "onlineapp:login"

    model=College
    template_name = 'onlineapp/college_detail.html'

    success_url = reverse_lazy('onlineapp:college_detail.html')
    def get_object(self, queryset=None):
        #we are getting refernece of clg
        return get_object_or_404(College, **self.kwargs)

    def get_context_data(self, **kwargs):
        context = super(CollegeDetailView,self).get_context_data(**kwargs)
        #import ipdb
        #ipdb.set_trace()
        college = context.get('college')
        students = list(college.student_set.order_by("-mocktest1__total"))
        context.update({'students':students,'user_permissions':self.request.user.get_all_permissions()})
        return context



class  CreateCollegeView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    login_url = "onlineapp:login"
    permission_required="onlineapp.add_college"
    permission_denied_message="User des not have permission to create a college"
    raise_exception=True
    model=College
    form_class = Addcollege
    success_url = reverse_lazy('onlineapp:college_html')


class UpdateCollegeView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    login_url = "onlineapp:login"
    permission_required="onlineapp.change_college"
    permission_denied_message = "user does not have permission to change a college"
    model=College

    form_class = Addcollege

    template_name = 'onlineapp/college_form.html'

    success_url = reverse_lazy('onlineapp:college_html')

    def get_object(self,queryset=None):
        #return get_object_or_404(College,**self.kwargs)
        return get_object_or_404(College,**{'pk': self.kwargs.get('pk')})

    def get_context_data(self,**kwargs):
        context=super(UpdateCollegeView,self).get_context_data(**kwargs)
        #import ipdb
        #ipdb.set_trace()
        college=context.get('college')
        students=list(college.student_set.order_by('-mocktest1__total'))
        context.update({
            'students':students,
            #'user_permissions':self.request.user.get_all_permissions()
        })
        return context

class DeleteCollegeView(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    login_url = "onlineapp:login"
    permission_required = "onlineapp.delete_college"
    permission_denied_message = "user does not have permission to delete a college"
    model = College
    template_name = 'onlineapp/delete.html'
    success_url = reverse_lazy('onlineapp:college_html')

    def get_object(self, queryset=None):
        return get_object_or_404(College, **self.kwargs)

onlineapp/views/student.py
from onlineapp.models import *
from django.views import View
from onlineapp.models import *
from django.shortcuts import *
import ipdb
from django.views.generic import *
from django import forms
from onlineapp.forms import *
from django.urls import *
from django.contrib.auth.mixins import *
class CreateStudentView(LoginRequiredMixin,CreateView):
    login_url = "onlineapp:login"
    model = Student
    form_class = studentform
    permission_required = "onlineapp.add_student"
    permission_denied_message = "user does not have permission to add a student"
    #template_name = 'onlineapp/student_form.html'

    def get_context_data(self, **kwargs):
        context = super(CreateStudentView, self).get_context_data(**kwargs)
        test_form = MockTestForm()
        context.update({
            'student_form': context.get('form'),
            'test_form': test_form,
        })
        return context

    def post(self, request, *args, **kwargs):
        login_url = "onlineapp:login"
        college = get_object_or_404(College, pk=kwargs.get('pk'))
        student_form = studentform(request.POST)
        test_form = MockTestForm(request.POST)

        if student_form.is_valid():
            student = student_form.save(commit=False)
            student.college = college
            student.save()

            if test_form.is_valid():
                score = test_form.save(commit=False)
                score.total = sum(test_form.cleaned_data.values())
                score.student = student
                score.save()

        return redirect('onlineapp:college_detail_html',college.id)



class UpdateStudentView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    login_url = "onlineapp:login"
    permission_required = "onlineapp.change_student"
    permission_denied_message = "user does not have permission to change a student"
    model = Student
    form_class = studentform
    template_name = 'onlineapp/student_form.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateStudentView, self).get_context_data(**kwargs)
        student_form = context.get('student')
        test_form =MockTestForm(instance=student_form.mocktest1)
        context.update({
            'student_form': context.get('form'),
            'test_form': test_form,
        })

        return context

    def post(self, request, *args, **kwargs):
        login_url = "onlineapp:login"
        student = Student.objects.get(pk=kwargs.get('pk'))
        form = studentform(request.POST, instance=student)
        test_form = MockTestForm(request.POST, instance=student.mocktest1)
        test = test_form.save(False)
        test.total = sum(test_form.cleaned_data.values())
        form.save()
        test_form.save()
        return redirect("onlineapp:college_detail_html", self.kwargs.get('college_id'))


class DeleteStudentView(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    login_url = "onlineapp:login"
    permission_required = "onlineapp.delete_student"
    permission_denied_message = "user does not have permission to delete a student"
    model=Student

    success_url = reverse_lazy('onlineapp:college_html')

    def get(self,request,*args,**kwargs):
        return self.post(request,args,kwargs)

    def post(self, request, *args, **kwargs):
        self.delete(request, args, kwargs)
        return redirect("onlineapp:college_detail_html", self.kwargs.get('college_id'))

onlineapp/templates/onlineapp/app.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>onlineapp</title>
</head>
<body>
Hello h r u
</body>
</html>

onlineapp/templates/onlineapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> django forms </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

onlineapp/templates/onlineapp/clgorder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>college</title>
    <script>
</script>
</head>
<body>
<center>
    <table border="1">
<!--{% block caption %}
        <caption>{{caption}}</caption>
        {% endblock %}-->

{% for i in c %}
<tr>

    <td>{{i.acronym}}</td>
    <td>{{i.student__name}}</td>
    <td>{{i.student__mocktest1__total}}</td>

</tr>
        {% endfor %}
    </table>
</center>
</body>
</html>

onlineapp/templates/onlineapp/college.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>college</title>
</head>
<body>
<center>
    <table border="1">
{% block caption %}
        <caption>{{caption}}</caption>
        {% endblock %}
 <!--{% block c %}
       <h>{{c.name}}</h>
        {% endblock %}-->

<tr>

    <td>{{c.name}}</td>
    <td>{{c.email}}</td>
     <td>{{c.db_folder}}</td>
    <td>{{c.college__name}}</td>

</tr>
    </table>
</center>
</body>
</html>

onlineapp/templates/onlineapp/college_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    {% include 'onlineapp/css.html' %}

     <link href="css/bootstrap.min.css"rel="stylesheet"media="screen">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Student</title>
    <script>
</script>
</head>
<body>
   <form>
        <fieldset>
             &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'onlineapp:logout'%}">Log Out</a>
               <center><h3>Students in {{college.name}}</h3></center>
             {% if 'onlineapp.add_student' in user_permissions %}
             <div class="form-group">
                <button><a href="{% url 'onlineapp:college_detail.html' college.id %}">Add Student</a></button>
            </div>
            {% endif %}
            <br>
            <br>


            <table class="table">
<tr>
    <th>Name</th>
    <th>Email</th>
    <th>DB_folder</th>
    <th>Dropped Out</th>
    <th>Marks</th>
    <th>Action</th>
</tr>
{% for i in students %}
<tr>

    <td>{{i.name}}</td>
    <td>{{i.email}}</td>
    <td>{{i.db_folder}}</td>
    <td>{{i.dropped_out}}</td>
    <td>{{i.mocktest1.total}}</td>
{% if 'onlineapp.change_student' in user_permissions and 'onlineapp.delete_student' in user_permissions %}
          <td>
                <a href="{% url 'onlineapp:edit_student' i.college.id i.id %}">Edit</a> |
                <a href="{% url 'onlineapp:delete_student' i.college.id i.id %}">Delete</a>
            </td>
    {% endif %}
</tr>
        {% endfor %}
    </table>
            </fieldset>
    </form>

</body>
</html>

onlineapp/templates/onlineapp/college_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Add College</legend>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Enter Name</label>
                    {{ form.name }}</div>
                <div class="from-group">
                    <label for="{{ form.location.id_for_label}}">Enter location</label>
                    {{ form.location }}
                </div>
                <div class="from-group">
                    <label for="{{ form.acronym.id_for_label}}">Enter acronym</label>
                    {{ form.acronym}}
                </div>
                 <div class="from-group">
                    <label for="{{ form.contact.id_for_label}}">Enter contact</label>
                    {{ form.contact}}
                </div>
                <input type="submit" value="submit">
            </fieldset>
        </form>
    </div>
</div>
</body>
</html>

onlineapp/templates/onlineapp/college_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% include 'onlineapp/css.html' %}

     <link href="css/bootstrap.min.css"rel="stylesheet"media="screen">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>college</title>
    <script>
</script>
</head>
<body>

    <form>
        <fieldset>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'onlineapp:logout'%}">Log Out</a>
      <center> <h3>Colleges</h3></center>
            {% if 'onlineapp.add_college' in user_permissions %}
            <div class="form-group">
                <button><a href="{% url 'onlineapp:add_colleges'%}">Add College</a></button>
            </div>
            {% endif %}
            <br>
            <br>

    <table class="table">
        <tr>
            <th>Name</th>
            <th>Acronym</th>
            <th>Location</th>
            <th>Action</th>
        </tr>
{% for i in jails %}
<tr>

    <td><a href="{% url 'onlineapp:college_detail_html' i.id %}">{{i.name}}</a></td>
        <td>{{i.acronym}}</td>
    <td>{{i.location}}</td>
    {% if 'onlineapp.change_college' in user_permissions and 'onlineapp.delete_college' in user_permissions %}
        <td>
                <a href="{% url 'onlineapp:edit_college' i.id %}">Edit</a> |
                <a href="{% url 'onlineapp:delete_college' i.id %}">Delete</a>
            </td>
    {% endif %}
      </tr>
        {% endfor %}
    </table>
             </fieldset>
    </form>

</body>
</html>

onlineapp/templates/onlineapp/css.html
<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
</html>

onlineapp/templates/onlineapp/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
</head>
<body>
<div class="container">
        <h1><b>Delete College</b></h1>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
</body>
</html>

onlineapp/templates/onlineapp/login.html
{% extends 'onlineapp/base.html' %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-fixed-top bg-primary">
    <a class="navbar-brand" href="#">Online App</a>
    <!--{% if request.user.is_authenticated-->
</nav>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Log in</legend>
                <div class="form-group">
                    <label for="{{ form.user_name.id_for_label}}">Enter Username</label>
                    {{ form.username}}
                </div>
                 <div class="forlm-group">
                    <label for="{{ form.password.id_for_label}}">Enter Password</label>
                    {{ form.password}}
                </div>
                <input type="submit" value="Login">
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

onlineapp/templates/onlineapp/marks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>college</title>
    <script>
function myFunction(marks) {
    document.getElementById("b").innerHTML = marks;
}
</script>
</head>
<body>
<center>
    <table border="1">
<!--{% block caption %}
        <caption>{{caption}}</caption>
        {% endblock %}-->

{% for i in c %}
<tr>

    <td>{{i.student__name}}</td>
    <td>{{i.problem1}}</td>
    <td>{{i.problem2}}</td>
    <td>{{i.problem3}}</td>
    <td>{{i.problem4}}</td>
     <td><button id="b" type="button" onclick="alert({{i.total}})">Total</button>
     </td>
</tr>
        {% endfor %}
    </table>
</center>
</body>
</html>

onlineapp/templates/onlineapp/mocktest_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Add College</legend>
                <div class="form-group">
                    <label for="{{ form.problem1.id_for_label }}">Enter Problem1 Marks</label>
                    {{ form.problem1 }}</div>
                <div class="from-group">
                    <label for="{{ form.problem2.id_for_label}}">Enter problem2 Marks</label>
                    {{ form.problem2 }}
                </div>
                <div class="from-group">
                    <label for="{{ form.problem3.id_for_label}}">Enter problem3 marks</label>
                    {{ form.problem3}}
                </div>
                 <div class="from-group">
                    <label for="{{ form.problem4.id_for_label}}">Enter problem4 marks</label>
                    {{ form.problem4}}
                </div>
                <input type="submit" value="submit">
            </fieldset>
        </form>
    </div>
</div>
</body>
</html>

onlineapp/templates/onlineapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
      {% include 'onlineapp/css.html' %}

    <title>Signup</title>
</head>
<body>
<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Sign Up</legend>
                <div class="form-group">
                    <label for="{{ form.first_name.id_for_label }}">Enter Firstname</label>
                    {{ form.first_name }}</div>
                <div class="from-group">
                    <label for="{{ form.last_name.id_for_label}}">Enter Lastname</label>
                    {{ form.last_name }}
                </div>
                <div class="from-group">
                    <label for="{{ form.username.id_for_label}}">Enter Username</label>
                    {{ form.username}}
                </div>
                 <div class="from-group">
                    <label for="{{ form.password.id_for_label}}">Enter Password</label>
                    {{ form.password}}
                </div>
                <input type="submit" value="Signup">
            </fieldset>
        </form>
    </div>
</div>
</body>
</html>

onlineapp/templates/onlineapp/student_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<div class="container">
    <div class="col-xs-6 col-xs-offset-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend>Add Student</legend>
                <div class="form-group">
                    <label for="{{ form.name.id_for_label }}">Enter Name</label>
                    {{ form.name }}</div>
                <div class="from-group">
                    <label for="{{ form.email.id_for_label}}">Enter email</label>
                    {{ form.email }}
                </div>
                <div class="from-group">
                    <label for="{{ form.db_folder.id_for_label}}">Enter db_folder</label>
                    {{ form.db_folder}}
                </div>
                 <div class="from-group">
                    <label for="{{ form.dropped_out.id_for_label}}">Enter droppedout</label>
                    {{ form.dropped_out}}
                </div>
                <input type="submit" value="submit">
            </fieldset>
        </form>
    </div>
</div>-->

<form method="post">
    {% csrf_token %}
    {{ student_form.name }}
    {{ student_form.email }}
    {{ student_form.db_folder }}
    {{ student_form.dropped_out }}
    {{ test_form.as_p }}

    <input type="submit" value="Submit">
</form>
</body>
</html>